-- MySQL Script generated by MySQL Workbench
-- Mon Oct 23 11:20:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`main_page_text`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`main_page_text` ;

CREATE TABLE IF NOT EXISTS `mydb`.`main_page_text` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `h2` LONGTEXT NOT NULL,
  `content` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`about_us`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`about_us` ;

CREATE TABLE IF NOT EXISTS `mydb`.`about_us` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`menu` ;

CREATE TABLE IF NOT EXISTS `mydb`.`menu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `page_name` VARCHAR(45) NOT NULL,
  `url` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`portfolio_showcase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`portfolio_showcase` ;

CREATE TABLE IF NOT EXISTS `mydb`.`portfolio_showcase` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `image_link` LONGTEXT NOT NULL,
  `url` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`qna`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`qna` ;

CREATE TABLE IF NOT EXISTS `mydb`.`qna` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(150) NOT NULL,
  `answer` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
